In [1]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6],[5,4]), dtype=float) #network input values
Y = np.array(([92], [86], [89],[90]), dtype=float) #network output values
y = Y/100 #Actual output
m,n=np.shape(Y)
print(m)
print(n)
print(X)
print(y)
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))
#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)
#Variable initialization
epoch=100000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = 2 #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))
print(wh)
print(bh)
print(wout)
print(bout)
for i in range(epoch):
#Forward Propogation  Dot product + bias
    h_ip=np.dot(X,wh) + bh
    h_act = sigmoid(h_ip) # Activation function
    o_ip=np.dot(h_act,wout) + bout
    output = sigmoid(o_ip)
    #Backpropagation
    # Error at Output layer # Error at o/p
    
    Eo = y-output
    outgrad = derivatives_sigmoid(output)
    d_output = Eo* outgrad # Errj=Oj(1-Oj)(Tj-Oj)
    # Error at Hidden later 
    # .T means transpose
    Eh = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(h_act) # How much hidden layer wts contributed to error
    d_hidden = Eh * hiddengrad # Dotproduct of nextlayererror and currentlayerop
    wout += h_act.T.dot(d_output) *lr
    wh += X.T.dot(d_hidden) *lr
print(wh)
print(wout)
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

4
1
[[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]
[[0.92]
 [0.86]
 [0.89]
 [0.9 ]]
[[0.70167691 0.23242709 0.68088797]
 [0.96205592 0.80850447 0.67754469]]
[[0.27449772 0.08596743 0.06379733]]
[[0.15878937]
 [0.16125049]
 [0.20000643]]
[[0.68242459]]
[[0.69940163 0.06484585 0.35984818]
 [0.94531541 0.1811335  0.12593137]]
[[-0.66433484]
 [ 1.08755635]
 [ 1.45934803]]
Normalized Input: 
[[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]
 [0.9 ]]
Predicted Output: 
 [[0.9028777 ]
 [0.87093641]
 [0.89607202]
 [0.89803906]]
